services:
  - type: web
    name: spreadcalculadora
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
    startCommand: gunicorn spreadsite.wsgi:application
    envVars:
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: spreadsite.settings
