services:
  - type: web
    name: spreadcalculadora
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
    startCommand: gunicorn spread_calculadora.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: spread_calculadora.settings
