# Generated by Django 5.2.1 on 2025-05-11 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_abertura', models.FloatField()),
                ('short_abertura', models.FloatField()),
                ('spread_abertura', models.FloatField()),
                ('spot_fechamento', models.FloatField()),
                ('short_fechamento', models.FloatField()),
                ('spread_fechamento', models.FloatField()),
                ('lucro', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
