# Generated by Django 5.2.1 on 2025-05-27 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('spot_abertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_abertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spread_abertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spot_fechamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_fechamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spread_fechamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Spread',
                'verbose_name_plural': 'Registros de Spread',
                'ordering': ['-data_registro'],
            },
        ),
    ]
