# Generated by Django 5.2.1 on 2025-05-12 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_alter_spreadregistro_lucro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadregistro',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='spreadregistro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='spreadregistro',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spreadregistro',
            name='lucro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spreadregistro',
            name='short_abertura',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spreadregistro',
            name='short_fechamento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spreadregistro',
            name='spot_abertura',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spreadregistro',
            name='spot_fechamento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spreadregistro',
            name='spread_abertura',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spreadregistro',
            name='spread_fechamento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
